// Generated by CoffeeScript 1.11.1
(function() {
  if ((typeof exports !== "undefined" && exports !== null) && (typeof require !== "undefined" && require !== null)) {
    exports.ObjectTemplate = require('./ObjectTemplate');
    exports.TemplateConfig = require('./TemplateConfig');
  } else if (typeof window !== "undefined" && window !== null) {
    window.json2json = {};
  }

}).call(this);
